<?xml version="1.0"?>
<robot name="aerial_drone" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Include common macros and motor definition -->
  <xacro:include filename="$(find aerial_drone_base)/urdf/common_macro.xacro"/>
  <xacro:include filename="$(find aerial_drone_base)/urdf/motor.xacro"/>

<!-- *********************************************************************** -->
  <!-- Drone parameters -->
  <xacro:property name="body_mass" value="1.5"/>
  <xacro:property name="body_length" value="0.6"/>
  <xacro:property name="body_width" value="0.4"/>
  <xacro:property name="body_height" value="0.05"/>
  <xacro:property name="body_color" value="0.1 0.1 0.1 1"/>

  <xacro:property name="motor_mass" value="0.1"/>
  <xacro:property name="motor_radius" value="0.1"/>
  <xacro:property name="motor_length" value="0.05"/>
  <xacro:property name="motor_color" value="0.8 0.8 0.8 1"/>

  <xacro:property name="motor_offset_x" value="${body_length / 2}"/>
  <xacro:property name="motor_offset_y" value="${body_width / 2}"/>


  <!-- Joint parameters -->
  <xacro:property name="joint_limit" value="1.57"/>
  <xacro:property name="joint_effort" value="1000"/>
  <xacro:property name="joint_velocity" value="10"/>

<!-- *********************************************************************** -->
  <!-- Main body link -->

  <link name="dummy_link">
    <!-- Нет инерционных параметров для dummy_link -->
  </link>
  
  <joint name="dummy_to_base" type="fixed">
    <parent link="dummy_link"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="base_material">
        <color rgba="${body_color}"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="${body_mass}" x="${body_length}" y="${body_width}" z="${body_height}"/>
  </link>

<!-- *********************************************************************** -->
  <!-- Roll joint -->
  <joint name="roll_joint" type="revolute">
    <parent link="base_link"/>
    <child link="roll_frame"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-${joint_limit}" upper="${joint_limit}" effort="${joint_effort}" velocity="${joint_velocity}"/>
  </joint>

  <link name="roll_frame">
    <xacro:inertial_cylinder mass="0.01" length="0.01" radius="0.01"/>
  </link>

<!-- *********************************************************************** -->
  <!-- Pitch joint -->
  <joint name="pitch_joint" type="revolute">
    <parent link="roll_frame"/>
    <child link="pitch_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-${joint_limit}" upper="${joint_limit}" effort="${joint_effort}" velocity="${joint_velocity}"/>
  </joint>

  <link name="pitch_frame">
    <xacro:inertial_cylinder mass="0.01" length="0.01" radius="0.01"/>
  </link>

 <!-- *********************************************************************** -->
  <!-- Mounting motors with calculated positions -->
  <xacro:motor name="front_right_motor" mass="${motor_mass}" length="${motor_length}" radius="${motor_radius}" color="${motor_color}" origin="${motor_offset_x} ${motor_offset_y} 0"/>
  <xacro:motor name="front_left_motor" mass="${motor_mass}" length="${motor_length}" radius="${motor_radius}" color="${motor_color}" origin="-${motor_offset_x} ${motor_offset_y} 0"/>
  <xacro:motor name="rear_left_motor" mass="${motor_mass}" length="${motor_length}" radius="${motor_radius}" color="${motor_color}" origin="-${motor_offset_x} -${motor_offset_y} 0"/>
  <xacro:motor name="rear_right_motor" mass="${motor_mass}" length="${motor_length}" radius="${motor_radius}" color="${motor_color}" origin="${motor_offset_x} -${motor_offset_y} 0"/>

  <gazebo>
    <plugin name="ros_gz_control" filename="libros_gz_control.so">
        <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="mavlink_interface" filename="libgazebo_mavlink_interface.so">
        <robotNamespace>/</robotNamespace>
        <port>14560</port> <!-- Указать порт, который используется PX4 -->
    </plugin>
  </gazebo>


</robot>
